[package]
name = "texcreate"
version = "3.0.0-beta.1"
edition = "2021"
authors = ["Mustafif Khan"]
license = "MIT"
homepage = "https://mkproj.com"
repository = "https://github.com/MKProj/texcreate"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "4.0.0"
reqwest = "0.11.14"
structopt = "0.3.26"
texcore = { version = "0.4.11", features = ["texcreate_template"] }
texcreate_repo = { git = "https://github.com/MKProj/texcreate_repo", version = "0.1.0" }
tokio = { version = "1.25.0", features = ["full"] }
thiserror = "1.0.38"
toml = "0.7.2"
serde = { version = "1.0.152", features = ["derive"] }
termcolor = "1.2.0"
