packages = []

[project]
proj_name = "Project"
template = "basic"
repo = "mkproj"

[metadata]
author = "author"
date = "date"
title = "title"
fontsize = 11
papersize = "letterpaper"
doc_class = "article"
maketitle = true
