packages = ["listings"]

[project]
proj_name = "Project"
template = "basic"
repo = "mkproj"

[metadata]
author = "Mustafif Khan"
date = "2022-2023"
title = "The Basic Template"
fontsize = 11
papersize = "a4paper"
doc_class = "article"
maketitle = true
