[book]
authors = ["Mustafif Khan"]
language = "en"
multilingual = false
src = "src"
title = "Getting Started with TexCreate!"

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
curly-quotes = true
mathjax-support = false
copy-fonts = true
no-section-label = true
git-repository-url = "https://github.com/MKProj/texcreate"
git-repository-icon = "fa-github"

[output.html.print]
enable = true    # include support for printable output
page-break = true # insert page-break after each chapter
